// This file was created from the auto item template project generated by Visual Studio
namespace AutoItemTemplate
{
#if false
/* Go to Project -> Export Template and select Item template and the project as AutoItemTemplate and click next.
 * Fill in the details appropriately and then click finish. If you selected the template to not be imported automatically 
 * then you will need copy it yourself from the exported directory C:\Users\dummyUser\Documents\Visual Studio 2022\My Exported Templates 
 * to the template directory C:\Users\dummyuser\Documents\Visual Studio 2022\Templates\ItemTemplates\Visual C#
*/
#endif

    /// <summary>
    /// Purpose:
    /// Created By: Jdeane
    /// Created On: 1/9/2022 8:54:41 PM
    /// </summary>
    public class Class1
    {

    }
}